### ISSUE TITLE
求助作者

### ISSUE THREAD

**Issue by Mu-slackoff** [mowangshuying/CppQtWeChat#1]
有没有注释详细的源码

**Comment by mowangshuying** [comment]
这个源码没有写太多注释，可以运行起来边调试，理解下代码，代码理解起来挺容易的。

**Comment by Mu-slackoff** [comment]
> 这个源码没有写太多注释，可以运行起来边调试，理解下代码，代码理解起来挺容易的。

我现在刚刚接触qt，有什么教程可以推荐吗？

**Comment by mowangshuying** [comment]
B站很多qt视频教程，选一个稍微简单点看就行，先看完一个简单的，再找其他。
